---

- name: "httpd-restart"
  when: ansible_os_family == "RedHat"
  service:
    name: httpd
    state: restarted
    enabled: true

- name: "apache2-restart"
  when: ansible_os_family == "Debian"
  service:
    name: apache2
    state: restarted
    enabled: true

